% --- INICIO DE PLANTILLA PERSONALIZADA ---
\documentclass[oneside,11pt]{Latex/Classes/PhDthesisPSnPDF}

% --- Paquetes Originales ---
\usepackage{blindtext}
\usepackage{actuarialangle} 
\usepackage{tabularx}
\usepackage{float}
\usepackage{multirow, array}
\usepackage[usenames,dvipsnames,svgnames,table]{xcolor}
\usepackage{longtable}
\usepackage{latexsym,amsmath,amssymb,amsfonts}
\usepackage{enumitem}
\usepackage{xparse}
\usepackage{booktabs}
\usepackage[round, sort, numbers]{natbib}  
\usepackage{adjustbox}
\usepackage[utf8]{inputenc}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{hyperref}
\usepackage{cleveref}

% Definición de colores
\definecolor{miblue}{RGB}{68, 114, 196}

% --- CAMBIO CRÍTICO 1: Usar \input para macros en el preámbulo ---
% \include da problemas antes del begin document. \input es seguro.
\input{Latex/Macros/MacroFile1}

% --- Definiciones de seguridad (por si la clase falla al cargar alguna variable) ---
\providecommand{\facultad}[1]{\def\lafacultad{#1}}
\providecommand{\escudofacultad}[1]{\def\elescudo{#1}}
\providecommand{\degree}[1]{\def\elgrado{#1}}
\providecommand{\director}[1]{\def\eldirector{#1}}
\providecommand{\lugar}[1]{\def\ellugar{#1}}
\providecommand{\degreedate}[1]{\def\lafecha{#1}}

% --- Configuración para bloques de código de R (Pandoc) ---

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                         DATOS (Conectados a RMarkdown)                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title{El comportamiento de las características musicales en las
canciones del género pop de los sellos discográficos de la plataforma de
Spotify en el período de 2015 a 2025.}
\author{Sebastian Soto \\ Valeria Ruza \\ Gabriel Ugas}

% Lógica para Facultad: Si la defines en el YAML la usa, si no, usa la default

\facultad{Facultad de Ciencias Económicas y Sociales \\ Escuela de
Estadistica y Ciencias Actuariales}
  \escudofacultad{Latex/Classes/Escudos/faces}

\degree{Computación I}
\director{Jesus Ochoa \\ Oliver Triveño}
\degreedate{Marzo 2026} 
\lugar{Caracas}

\portadatrue 

% Metadatos PDF
\keywords{}
\subject{}

% --- CORRECCIÓN PARA PANDOC NUEVO (Imágenes) ---
\makeatletter
\providecommand{\pandocbounded}[1]{#1}
\makeatother


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   DOCUMENTO                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}

\maketitle

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                  PRÓLOGO                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\frontmatter

% Puedes agregar dedicatorias desde el YAML si quieres, o dejarlas fijas aquí

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   ÍNDICES                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\setcounter{secnumdepth}{3}
\setcounter{tocdepth}{3}

\tableofcontents



\cleardoublepage

  \cleardoublepage       % Empieza en página derecha (estándar en tesis)
  \chapter*{Resumen}     % Crea el título "Resumen" sin numeración (Capítulo *)
  \addcontentsline{toc}{chapter}{Resumen} % (Opcional) Lo añade al índice
  
  El proyecto pretende atender al problema de la estandarización en las
canciones con sello de discográficas del género Pop, que afectan
negativamente a la nueva generación, enfocados en la parte estadística
del mismo, analizando las características de las canciones del género
Pop usando como referencia el dataset (Spotify 2015-2025) El objetivo es
comprobar que existe las estandarización en las características tecnicas
y sonoras de las canciones con sello discográficos del género Pop. Se
toman en cuenta varias variables en este caso:(loudness, energy, tempo,
danceability), se dividen en dos categorías sonoras y tecnicas, se
analizan las variables de cada categoría aparte usando cuadros que
muestren su coeficiente de variacion, media y curtos, se refelja en un
grafico de violin y por último gráficas de calor para contemplar la
correlación y ver si es alta o baja. Por último se analizan todos los
resultados y se determinaría si son o no estandarizadas las
canciones.             % Aquí se pega el texto que escribiste en el YAML
  
  \cleardoublepage

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   CONTENIDO (El Corazón)          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\mainmatter
\def\baselinestretch{1.5}

% --- CAMBIO CRÍTICO 2: Aquí RMarkdown inyecta todo tu texto ---
\chapter*{Introducción}

La industria musical contemporánea se caracteriza por el dominio
oligopólico de grandes discográficas, que controlan la mayoría del
mercado pop global. Este proyecto investiga la hipótesis de que estas
``majors'' promueven una estandarización de las características
musicales, limitando la diversidad sonora disponible para el público
juvenil.

A través del análisis estadístico descriptivo del dataset
\textbf{\emph{Spotify 2015-2025}}, se examinan variables técnicas
(loudness, energy) y sonoras (tempo, danceability) de canciones pop con
sello de discográficas. El objetivo es determinar, mediante análisis de
dispersión, distribución y correlación, si existe una homogeneización
sistemática en las producciones comerciales que pudiera condicionar los
patrones de consumo y la creatividad musical actual.

\chapter{Planteamiento del Problema}

Desde finales de los sesenta, cuando se habla de ``Pop'' se refiere,
sobre todo, a la música orientada al consumo rápido y dirigida a los
jóvenes. Canciones de duración corta con ritmos contagiosos, para
alcanzar un éxito popular y comercial dirigido a la mayor cantidad de
público posible y jóvenes. Como escribe John Seabrook ``La fábrica de
canciones. Cómo se hacen los hits''.

Ya que el Pop absorbe características de otros géneros para mantener su
éxito y recurre a letras y melodías repetitivas, románticas y
melancólicas. Esta tendencia cambiante e imitadora, junto con que esté
dirigido a una cantidad de público muy extensa y sobre todo enfocado en
Jóvenes. Influye profundamente en la forma de pensar, sentir y
comportarse de gran parte de la población y los adolescentes, a menudo
fomentando la imitación, según apuntan International Journal of Arts \&
Education Research.

También, la industria musical es posiblemente uno de los mercados más
competitivos. Los sellos discográficos son empresas que contratan
artistas, financian grabaciones, comercializan la música y coordinan la
distribución. Según una investigación presentada por Juan Francisco
Peñaloza Cubillos, de la Pontificia Universidad Javeriana, concluye que
el mercado musical es un oligopolio entre las grandes compañías
discográficas.

``Actualmente la industria de la música es controlada por tres grandes
compañías discográficas multinacionales también llamadas majors, tanto a
nivel internacional como a nivel nacional, siendo Sony Music, Universal
Music Group y Warner Music Group los que lideran el mercado mundial de
la industria de la música, como también a la gran mayoría de sus
artistas.''

Entonces tomando en cuenta el hecho que el género Pop influencia en la
manera de pensar de los jóvenes y que las discográficas dominan el
mercado, Podemos decir que las canciones con sellos de discográficas
pueden controlar la forma de pensar de los Jóvenes y por consiguiente si
las discográficas tienden a estandarizar las características sonoras y
técnicas de las canciones, están imponiendo al público Juvenil un modelo
único de consumo, lo que los lleva a tener limitaciones en el acceso a
la diversidad musical y a la imitación pasiva.\\

Argumento final. Debido a esto, se plantea las siguientes preguntas de
investigación:\\

\textbf{1.} ¿Qué cantidad de canciones hay por discográfica?\\

\textbf{2.} ¿Las variables analizadas demuestran un comportamiento
similar a lo largo del tiempo, con lo que podemos determinar que las
disqueras musicales comercializan canciones estandarizadas?\\

\textbf{3.} ¿Qué comportamiento demuestran las variables
estandarizadas?\\

\section{Justificación}

Este problema, que relaciona dos temas diferentes nos permite como
estadísticos aplicar el conocimiento del área de Estadística I, como lo
es la estadística descriptiva (Gráficas, Histogramas, matices de
correlación, coeficiente de variación), a través de los lenguajes
estudiado en Computación I como lo es R, aplicando el filtrado y
limpieza del dataset, aplicación de funciones matemáticas y creación de
gráficas, todo en una investigación que se puede adaptar a la
realidad.\\

\section{Objetivos}

\subsection{Objetivo General}
\begin{itemize}
  \item{ Determinar el comportamiento de las características musicales en las canciones del género pop de los sellos discográficos de la plataforma de Spotify en el período de 2015 a 2025.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{Identificar las discográficas con mayor cantidad de canciones publicadas del género Pop por entre 2015 y 2025.}
  \item{Describir la metricas de las variables técnicas y sonoras de las canciones pop de los sellos discograficos.}
  \item{Observar el comportamiento de las características entre las discográficas.}
  \item{Establecer las correlaciones entre las caracteristicas sonoras y técnicas de las canciones del género Pop.}
\end{itemize}

\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal abarca las características musicales que
componene cada canción\\

\subsection{Vertical}

La cobertura vertical abarca los 85.000 datos del dataset, que son las
canciones, y las caracterísitcas de todas las canciones, de 2015 a 2025.

\begin{table}[h!]
\centering
\caption{Variables consideradas} 
\resizebox{12cm}{!} {
\begin{tabular}{llp{9cm}}
  \hline
\textbf{Tipo} &\textbf{Variable} &\textbf{Definición} \\ 
  \hline
  Categórica & Label &  Sello discográfico de cada canción \\
  Numérica  & Loudness &  Medida de presión sonora \\
  Numérica & Energy & Intensidad perceptiva, el ruido espectral y la tasa de entropía \\
  Numérica  & Tempo & Velocidad del pulso \\
  Numérica  & Danceability & Regularidad del ritmo y la fuerza del pulso \\
   \hline
\end{tabular}
}
\end{table}

\section{Periodo de Referencia}

Usando el Dataset Spotify 2015-2025, se toma en cuenta desde el 2015 al
2025.

\chapter{Marco Teórico}

\section{Bases Teóricas}

El marco teórico de esta investigación se construye sobre tres pilares
fundamentales que vinculan la industria musical con el comportamiento
social:

\begin{enumerate}
\item \textbf{Naturaleza del Pop y Control Social:}Se define el Pop no solo como género, sino como un producto de consumo rápido diseñado para la masa juvenil. Su capacidad de absorción y repetición melódica actúa como un mecanismo que influye en la forma de pensar y sentir de los adolescentes, fomentando la imitación pasiva.
  
  \item \textbf{Estructura de Mercado (Oligopolio):}La industria no es un campo diverso, sino un oligopolio dominado por tres grandes sellos (majors): Sony Music, Universal Music Group y Warner Music Group. Estas corporaciones controlan la producción, distribución y el éxito comercial a nivel global.
  
   \item \textbf{Estandarización y Limitación Cultural:} La relación entre el dominio de las majors y las características del Pop sugiere una estandarización sonora. Al imponer modelos métricos y rítmicos uniformes, las discográficas limitan el acceso a la diversidad musical, condicionando al público a un modelo único de consumo.
 \end{enumerate}

Para el análisis estadístico, esta base es crucial porque transforma
conceptos abstractos (influencia y control) en variables medibles. Lo
que permite justificar por qué una baja dispersión o una alta
correlación en los datos no son coincidencias técnicas, sino evidencia
de una estrategia comercial dirigida a homogeneizar el gusto juvenil.

\subsection{Características Sonoras de una Canción}

Describen qué se siente o cómo suena la música y se definen por cuatro
cualidades fundamentales del sonido:

\begin{itemize}
\item
  \textbf{Tempo (BPM):} Es la medida de la velocidad de la pieza
  musical, expresada en pulsaciones por minuto (Beats Per Minute).
  Representa la frecuencia del ``pulso'' constante que el oyente percibe
  como referencia temporal básica de la obra.
\item
  \textbf{Danceability (Bailabilidad):} Es una métrica compuesta que
  describe qué tan adecuada es una pista para bailar basándose en una
  combinación de elementos musicales.
\end{itemize}

\subsection{Características Técnicas y de Producción de una Canción.}

Se refieren a los datos crudos, la calidad del archivo y los parámetros
de producción.

\begin{itemize}
\item
  \textbf{Loudness (Sonoridad):} Magnitud que cuantifica la presión
  sonora promedio de una señal de audio, expresada en decibelios (dB).
  Refleja la amplitud física del sonido y su nivel de volumen relativo
  dentro de una escala técnica.
\item
  \textbf{Energy (Energía):} Medida de la intensidad perceptiva y la
  actividad dinámica de una pieza musical. Se fundamenta en atributos
  como el rango dinámico, la tasa de ruido espectral y el entusiasmo
  auditivo que transmite la composición.
\end{itemize}

\subsection{Estadística Descriptiva}

La presente investigación emplea la estadística descriptiva para
resumir, analizar y caracterizar un conjunto de datos, permitiendo una
interpretacion detallada y estructurada de su comportamiento. Para ello
de aplicararn los siguientes indicadores :

\begin{enumerate}
  \item \textbf{Medidas de Tendencia Central:} Se utiliza para identificar el perfil promedio de las canciones pop. En las características técnicas (como loudness y duration), permiten establecer la duración y potencia estándar que la industria considera óptimas para la radiofusión. En las características sonoras (como tempo y danceability), definen el ritmo y la estructura melódica predominante, permitiendo observar si las discográficas convergen un modelo único diseñado para maximizar la aceptación del público juvenil.
  
  \textbf{Media Muestral}
    $$\bar{x} = \frac{1}{n} \sum_{i=1}^{n} x_i$$
    \bigskip
 
 \item  \textbf{Medidas de Dispersión:} Mediante el coeficiente de variación, se analiza la dispersión en las características técnicas y sonoras, permitiendo analizar si los datos son homogéneos o heterogéneos en la estructura musical del pop.
 
 
 \textbf{Coeficiente de Variación}
$$CV = \frac{\sigma}{\bar{x}} \times 100$$
\bigskip
 
\item \textbf{Medidas de la Forma (Distribución):} A partir de la curtosis, se evalúa el grado de concentración de cada una de las características técnicas y sonoras. Esto resulta fundamental para identificar si existe una homogeneización sistemática en las producciones comerciales.


\textbf{Curtosis}
$$g_2 = \frac{\sum (x_i - \bar{x})^4}{n \cdot s^4} - 3$$
 \bigskip
 
 Para representar de forma gráfica la  curtosis de los tados se utiliza el Histograma con Estimación de Densidad de Kernel (KDE). Esta herramienta permite visualizar de forma directa, la estructura que adoptan los datos en la distribución, facilitando la identificación de niveles de concentración en las características analizadas.
\end{enumerate}

\chapter{Marco Metódico}

En esta sección se presentan las metodologías y las pruebas estadísticas
implementadas para validar el planteamiento inicial.\\
Se especifica el procesamiento de la fuente de datos 18. Spotify
2015-2025.csv, las técnicas para verificar la presencia de datos nulos,
de limpieza (de ser necesario) y los análisis de estadística
descripitiva para las variables de interés en el estudio.\\
El análisis se ha realizado utilizando el lenguaje de programación R
(version 4.5.2) bajo el entorno de desarrollo RStudio, aplicando el
paradigma ``Tidyverse'' para la manipulacion de los datos\\

\section{Bases metódicas utilizadas en el trabajo de investigación}

El diseño de la investigación es de cáracter \textbf{cuantitativo} y
\textbf{descriptivo}, dado que se analizan las variables númericas de
las características de las canciones del género Pop agrupadas por su
Discográfica, en la plataforma de Spotify en el período de 2015 a 2025.
A continuación, se describen las etapas del procesamiento\\

\subsection{Procesamiento y Limpieza de Datos}

La calidad de los resultados depende directamente de la entrada de datos
de la manera más integra. Estos procesos se basa en la carga de los
datos del archivo \textbf{18. Spotify 2015-2025.csv} y la detección de
los valores nulos.\\

Adicionalmente, se filtran los datos para enfocarnos en el
comportamiento de las características del género Pop y se seleccionaron
las columnas de interés. También los registros \textbf{Independent} de
la columna \textbf{label} se descartan, ya que en esta investigación no
se consideran una discográfica.\\

\begin{verbatim}
## [1] "Registros totales del Dataset: 85000 | Cantidad de variables: 19"
\end{verbatim}

\begin{verbatim}
## [1] "Valores nulos por variable:"
\end{verbatim}

\begin{verbatim}
##         track_id       track_name      artist_name       album_name 
##                0                0                0                0 
##     release_date            genre      duration_ms       popularity 
##                0                0                0                0 
##     danceability           energy              key         loudness 
##                0                0                0                0 
##             mode instrumentalness            tempo     stream_count 
##                0                0                0                0 
##          country         explicit            label 
##                0                0                0
\end{verbatim}

\begin{verbatim}
## [1] "Registros totales del Dataset filtrado: 6231 | Cantidad de variables: 6"
\end{verbatim}

Se puede observar cómo, inicialmente, el dataset cuenta con 85000
registros y 19 variables, luego de la limpieza y filtrado, se obtiene un
dataset con 6 variables y 6231 datos. Adicionalmente, se observa que no
existen valores nulos en el dataset, lo que garantiza la integridad de
los datos para el análisis posterior.\\

\subsection{Fuente de datos y Período de Referencia}

Se utiliza el dataset \textbf{Spotify 2015-2025.csv}. En el análisis
descriptivo de la investigación solo se hace uso de \textbf{loudness,
energy, tempo, danceability} .Estas variables permiten observar de
manera clara los estandarés y el comportamiento de las características
de las canciones publicadas por las discograficas en la plataforma de
Spotify en el período que abarca desde el año 2015 hasta el año 2025.\\

\subsection{Operacionalización de Variables}

A continuación se presenta el cuadro de operacionalización de variables,
donde se especifican los objetivos específicos, junto con las variables
utilizadas en cada una. Además, de los indicadores y su instrumento de
análisis.

\begin{table}[!h]
\centering
\caption{\label{tab:operacionalizacion de variable}Estadisticas Descriptivas de las variables numéricas}
\centering
\fontsize{10}{12}\selectfont
\begin{tabular}[t]{lrrrr}
\toprule
Variables & Valor Minimo & Valor Maximo & Media & Desv. Estandar\\
\midrule
\cellcolor{gray!10}{loudness} & \cellcolor{gray!10}{-54.99} & \cellcolor{gray!10}{-1.00} & \cellcolor{gray!10}{-27.92} & \cellcolor{gray!10}{15.53}\\
energy & 0.02 & 0.99 & 0.50 & 0.28\\
\cellcolor{gray!10}{tempo} & \cellcolor{gray!10}{60.00} & \cellcolor{gray!10}{199.98} & \cellcolor{gray!10}{130.57} & \cellcolor{gray!10}{40.73}\\
danceability & 0.05 & 0.99 & 0.52 & 0.27\\
\bottomrule
\end{tabular}
\end{table}

\emph{analisis} Se observa a las variables técnicas en este etudio,
estas son: Energy, Loudness. Mientras que las variables sonoras en este
estudio son: Danceability y Tempo. Con esto se puede analizar cada
categoría por separado y aplicar los métodos de análisis
correspondientes a cada una.

Objetivo de estudio: Comparar el comportamiento de las variables entre
las discográficas. Loudness,Medida que cuantifica la presión sonora
promedio de una señal en decibelios (dB). Indica la amplitud física y el
nivel de volumen relativo de la pista bajo una escala técnica.\\

\chapter{Análisis de Resultados}

\{\small Este capítulo presenta los resultados obtenidos al aplicar las
metodologías descritas en el capítulo anterior, así como del análisis
estadístico descriptivo de las variables estudiadas y las ventajas y
desventajas al aplicar dichos tests.\}

\section{Cantidad de Canciones por discográfica}

En el análisis nos enfocammos en calcular el total de canciones por
discograficas, para saber si diferencia entre quienes son los que
publican mayor cantidad de canciones y utilizarlos para ver el
comportamiento de sus caracteristicas\\
A continuación, se presenta el gráfico con las siete Discograficas y sus
reproducciones totales.\\

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/Total de canciones por discograficas-1} \end{center}

Se observa como la cantidad de publicaciones de canciones de las
discográficas del género Pop entre 2015 y 2025 estan entre las 855 y 934
canciones. Lo que nos hace referencia de que no existe mucha diferencia
entre ellas, y se utilizaran todas para verificar el comportamiento de
sus caracteristicas.\\

\section{Clasificación de variables}

\section{Análisis de las variables Técnicas}

\subsection{Loudness}

\begin{table}[H]
\centering
\caption{\label{tab:Cuadro Análisis 1}Análisis de Estandarización}
\centering
\begin{tabular}[t]{ll>{\raggedright\arraybackslash}p{8cm}}
\toprule
Métrica & Valor & Interpretación\\
\midrule
\cellcolor{gray!10}{Media} & \cellcolor{gray!10}{-27.92} & \cellcolor{gray!10}{El valor central es -27.92 . Es el punto de referencia industrial.}\\
Coef. Variación (CV) & 55.61\% & Variabilidad detectada: Existe diversidad en los parámetros técnicos de las canciones.\\
\cellcolor{gray!10}{Curtosis} & \cellcolor{gray!10}{-1.19} & \cellcolor{gray!10}{Platicúrtica (Negativa): Los valores están dispersos, indicando falta de un estándar rígido.}\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Energy}

\begin{table}[H]
\centering
\caption{\label{tab:cuadro análsis 2}Análisis de Estandarización}
\centering
\begin{tabular}[t]{ll>{\raggedright\arraybackslash}p{8cm}}
\toprule
Métrica & Valor & Interpretación\\
\midrule
\cellcolor{gray!10}{Media} & \cellcolor{gray!10}{0.5} & \cellcolor{gray!10}{El valor central es 0.5 . Es el punto de referencia industrial.}\\
Coef. Variación (CV) & 55.08\% & Variabilidad detectada: Existe diversidad en los parámetros técnicos de las canciones.\\
\cellcolor{gray!10}{Curtosis} & \cellcolor{gray!10}{-1.18} & \cellcolor{gray!10}{Platicúrtica (Negativa): Los valores están dispersos, indicando falta de un estándar rígido.}\\
\bottomrule
\end{tabular}
\end{table}

\section{Análisis de variables sonoras}

\subsection{Tempo}

\begin{table}[H]
\centering
\caption{\label{tab:cuadro análsis 3}Análisis de Estandarización}
\centering
\begin{tabular}[t]{ll>{\raggedright\arraybackslash}p{8cm}}
\toprule
Métrica & Valor & Interpretación\\
\midrule
\cellcolor{gray!10}{Media} & \cellcolor{gray!10}{130.57} & \cellcolor{gray!10}{El valor central es 130.57 . Es el punto de referencia industrial.}\\
Coef. Variación (CV) & 31.19\% & Variabilidad detectada: Existe diversidad en los parámetros técnicos de las canciones.\\
\cellcolor{gray!10}{Curtosis} & \cellcolor{gray!10}{-1.22} & \cellcolor{gray!10}{Platicúrtica (Negativa): Los valores están dispersos, indicando falta de un estándar rígido.}\\
\bottomrule
\end{tabular}
\end{table}

\subsection{Danceability}

\begin{table}[H]
\centering
\caption{\label{tab:cuadro análsis 4}Análisis de Estandarización}
\centering
\begin{tabular}[t]{ll>{\raggedright\arraybackslash}p{8cm}}
\toprule
Métrica & Valor & Interpretación\\
\midrule
\cellcolor{gray!10}{Media} & \cellcolor{gray!10}{0.52} & \cellcolor{gray!10}{El valor central es 0.52 . Es el punto de referencia industrial.}\\
Coef. Variación (CV) & 52.27\% & Variabilidad detectada: Existe diversidad en los parámetros técnicos de las canciones.\\
\cellcolor{gray!10}{Curtosis} & \cellcolor{gray!10}{-1.19} & \cellcolor{gray!10}{Platicúrtica (Negativa): Los valores están dispersos, indicando falta de un estándar rígido.}\\
\bottomrule
\end{tabular}
\end{table}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-3-1} \end{center}

\section{Mapa de calor de correlación}

\begin{center}\includegraphics[width=0.9\linewidth,]{informe_files/figure-latex/unnamed-chunk-4-1} \end{center}

\section{Presentación de resultados}

Al observar los datos limpios nos damos cuenta que de 85000 datos del
dataset de espotify, nos quedamos con unos 6231 datos pertenecientes al
género pop, de los cuales el 87.82\% de los datos son de canciones con
sellos discográficos, y el número de canciones por discográfica son
parecidos con un rango de 79.

Seguidamente al observar el comportamento de las características
técnicas Loudness y Energy tienen un coeficiente de variación de 55.61\%
y 55.08\% respectivamente lo que indica que los datos tienen una
disperción baja con respecto a la media, osea son muy variados y una
curtosis de -1.19 y -1.18 respectivamente lo que indica que la gráfica
sigue una distribución platocurtica, osea no tiene ninguna tendencia
notable.

Al observar el comportamento de las características Sonoras Tempo y
Danceability tienen un coeficiente de variación de 31.19\% y 52.27\%
respectivamente lo que indica que los datos tienen una disperción baja
con respecto a la media, aunque el coeficiente de variación de Tempo es
menor a los otrrso al ser \textgreater{} 30 los dos son muy variados y
una curtosis de -1.22 y -1.19 respectivamente lo que indica que la
gráfica sigue una distribución platocurtica, osea no tiene ninguna
tendencia notable.

Por último al análizar la correlación de las variables con el mapa de
calor aparece una correlación muy cercana a 0 para todas las
correlaciones, lo que indica que las variables no dependen una de la
otra. las correlaciones están entre -0.02, -0.01, 0.00, 0.01 y 0.02.

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} La primera conclusión es que al contar la cantidad de
canciones por discógrafica, como no salieron cantidades muy similares
por discográfica, la opción más sensata es usar todas las discográficas
para el análisis de los datos y no perderse datos importantes.\\

\textbf{2.-} La segunda conclusión que sacamos es que al tener una alta
variabilidad al analizar las características de las canciones como
demuestra el coeficiente de variación y la forma de la gráfica
platocúrtica, son datos que no tienen ninguna tendencia significativa,
aparte de que no tienen correlaciones las variables, osea que no depende
una de otra, se puede decir que no hay una característica en común y no
hay estandarización.\\

\textbf{n.-} La última conclusión es que al no haber estandarización
visible y un comportamiento de los datos tan variado no se puede
determinar con exactitud el comportamiento de las características de las
canciones de las discográficas.\\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   REFERENCIAS                     %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mantenemos la estructura natbib de tu plantilla
\renewcommand{\bibname}{Lista de Referencias}
\bibliographystyle{apalike} 
\bibliography{bibliografia.bib} 

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                   APÉNDICES                       %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\end{document}
